version: '3.8'
services:
  postgres:
    image: postgres:14.5
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: development
    ports:
      - "5432:5432"
volumes:
  pg_data: